import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowRightLeft,
  ArrowUpRight,
  BarChart2,
  BarChart3,
  Bell,
  Box,
  Calendar,
  CheckCircle2,
  ChevronRight,
  Clock,
  CreditCard,
  Cpu,
  Database,
  DollarSign,
  Eye,
  ExternalLink,
  FileCheck,
  FileText,
  Filter,
  Hammer,
  HardHat,
  Key,
  Layers,
  LayoutDashboard,
  MapPin,
  Maximize2,
  Milestone,
  MoreVertical,
  PenTool,
  Scan,
  Search,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Split,
  Target,
  TrendingUp,
  UploadCloud,
  Wallet
} from "lucide-react";

export const appIcons = {
  activity: Activity,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrowRightLeft: ArrowRightLeft,
  arrowUpRight: ArrowUpRight,
  barChart2: BarChart2,
  barChart3: BarChart3,
  bell: Bell,
  box: Box,
  calendar: Calendar,
  checkCircle2: CheckCircle2,
  chevronRight: ChevronRight,
  clock: Clock,
  creditCard: CreditCard,
  cpu: Cpu,
  database: Database,
  dollarSign: DollarSign,
  eye: Eye,
  externalLink: ExternalLink,
  fileCheck: FileCheck,
  fileText: FileText,
  filter: Filter,
  hammer: Hammer,
  hardHat: HardHat,
  key: Key,
  layers: Layers,
  layoutDashboard: LayoutDashboard,
  mapPin: MapPin,
  maximize2: Maximize2,
  milestone: Milestone,
  moreVertical: MoreVertical,
  penTool: PenTool,
  scan: Scan,
  search: Search,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  shoppingCart: ShoppingCart,
  split: Split,
  target: Target,
  trendingUp: TrendingUp,
  uploadCloud: UploadCloud,
  wallet: Wallet
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof appIcons;

export function getIcon(name: IconName): LucideIcon {
  return appIcons[name];
}
